#!/bin/bash
set -euo pipefail

failure() {
  local lineno=$1
  local msg=$2
  local code=$3
  echo "Failed at $lineno: $msg"
  exit "$code"
}
trap 'failure ${LINENO} "$BASH_COMMAND" $?' ERR

yarn format
yarn lint
yarn type-check